version: "3"
services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "copsdjango"
    volumes:
      - "./:/cops"
    command: uwsgi --ini /cops/confs/uwsgi.ini
     
  nginx:
    image: nginx:latest
    volumes:
      - "./confs:/etc/nginx/conf.d"
    ports:
      # machine:container 
      - "83:80"
    links:
      - "django"
