version: "2"
services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "cops"
    volumes:
      - "./vol:/volume:Z" 
     
  nginx:
    image: nginx:latest
    volumes:
      - "./confs:/etc/nginx/conf.d"
    volumes_from:
      - "flask"
    ports:
      # machine:container 
      - "83:80"
    links:
      - "flask"
